imports:
    - { resource: parameters.yml }
    - { resource: framework.yml }
    - { resource: twig.yml }
    - { resource: assetic.yml }
    - { resource: doctrine.yml }
    - { resource: swiftmailer.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: services/filters.yml }
    - { resource: services/lis_view.yml }
    - { resource: services/actions.yml }
    - { resource: services/controllers.yml }
    - { resource: services/forms.yml }
    - { resource: dependencies/vardius.yml }
    - { resource: dependencies/nelmio_api_doc.yml }
    - { resource: dependencies/fos_user.yml }
    - { resource: dependencies/fos_rest.yml }
    - { resource: dependencies/fos_oauth_server.yml }
    - { resource: dependencies/jms_serializer.yml }
    # - { resource: snappy.yml }