#FORMS
services:
  form.type.users:
      class: AppBundle\Form\Type\UserType
      tags:
          - { name: form.type, alias: user }

  form.type.files:
      class: AppBundle\Form\Type\FileType
      tags:
          - { name: form.type, alias: file }

  form.type.tags:
      class: AppBundle\Form\Type\TagType
      tags:
          - { name: form.type, alias: tag }

  form.type.skills:
      class: AppBundle\Form\Type\SkillType
      tags:
          - { name: form.type, alias: skill }

  form.type.jobs:
      class: AppBundle\Form\Type\JobType
      tags:
          - { name: form.type, alias: job }

  form.type.projects:
      class: AppBundle\Form\Type\ProjectType
      tags:
          - { name: form.type, alias: project }

  form.type.social_medias:
      class: AppBundle\Form\Type\SocialMediaType
      tags:
          - { name: form.type, alias: social_media }

  form.type.categories:
      class: AppBundle\Form\Type\CategoryType
      tags:
          - { name: form.type, alias: category }

  form.type.articles:
      class: AppBundle\Form\Type\ArticleType
      tags:
          - { name: form.type, alias: article }

